export const ActionTypes = {
  FETCH_PEOPLE: 'FETCH_PEOPLE',
  FETCH_PEOPLE_SUCCESS: 'FETCH_PEOPLE_SUCCESS',
  FETCH_PEOPLE_FAIL: 'FETCH_PEOPLE_FAIL',

  CLICK_BUTTON: 'CLICK_BUTTON',
  RESET_STATE: 'RESET_STATE'
}
