export const ActionTypes = {
  FETCH_PEOPLE: 'FETCH_PEOPLE',
  FETCH_PEOPLE_SUCCESS: 'FETCH_PEOPLE_SUCCESS',
  FETCH_PEOPLE_FAIL: 'FETCH_PEOPLE_FAIL',

  FETCH_MORE_PEOPLE: 'FETCH_MORE_PEOPLE',
  FETCH_MORE_PEOPLE_SUCCESS: 'FETCH_MORE_PEOPLE_SUCCESS',
  FETCH_MORE_PEOPLE_FAIL: 'FETCH_MORE_PEOPLE_FAIL',

  FETCH_STARSHIPS_SUCCESS: 'FETCH_STARSHIPS_SUCCESS',

  FETCH_PLANET_SUCCESS: 'FETCH_PLANET_SUCCESS',
  RESET_PLANET: 'RESET_PLANET'
}
